#!/bin/bash
# Auto-generated by maestro
#SBATCH --job-name=thermo-hess
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --time=24:00:00
#SBATCH -p 32core_partition
#SBATCH --export=ALL,OMPI_MCA_plm=slurm
#SBATCH --output=/home/acc-2026-25595/260923/ethanol_combustion/runs/ethanol_thermo_work/thermo/hess/run/slurm-%j.out

set -euo pipefail

# --- Environment setup ---
case $- in *u*) __maestro_nounset=1 ;; *) __maestro_nounset= ;; esac
set +u
source /etc/profile >/dev/null 2>&1 || true
module load orca/v6.0.1
if [ -n "$__maestro_nounset" ]; then set -u; fi
unset __maestro_nounset
export OMP_NUM_THREADS="1"
export MKL_NUM_THREADS="1"
export OPENBLAS_NUM_THREADS="1"
export NUMEXPR_NUM_THREADS="1"

# --- Run ---
PYTHONPATH=/appl/share/maestro/maestro/src /appl/share/maestro/maestro/.venv/bin/python -m maestro.players.entry "/home/acc-2026-25595/260923/ethanol_combustion/runs/ethanol_thermo_work/thermo/hess/run" --backend slurm --job-id "${SLURM_JOB_ID:-}"
